package DatabaseOperations;

/**The class used to store some constants in the one place*/
public class ConstantsContainer {

    // Path to JSON with products
    public static String productsFilePath = "input_data/goods.json";

    // Path to JSON with sales
    public static String salesFilePath = "input_data/sales.json";

    // Path to JSON with salesmen
    public static String salesmenFilePath = "input_data/salesmen.json";

    // Path to json with Stock
    public static String stockFilePath = "input_data/stock.json";

    // Path to SQLite database file
    public static String databaseFilePath = "jdbc:sqlite:database/database.db";

    // The table generated by SQLite which we can't delete or modify, but it's seen in the table list
    public static String tableToIgnore = "sqlite_sequence";

    // The flag for the logger mode on/of
    public static boolean PROCESSING_LOGGER = true;



    // Starts of SQL Queries for the data insertion
    public static String productsInsertionInit = "INSERT INTO Products(ProductID, ProductName) VALUES ";
    public static String salesInsertInit = "INSERT INTO Sales(SaleID, SellerID, ProductID, QuantitySold, SaleDate) VALUES ";
    public static String salesmenInsertInit = "INSERT INTO Sellers(SellerID, FirstName, LastName) VALUES ";
    public static String stockInsertInit = "INSERT INTO Stock(SellerID, ProductID, Price, Quantity) VALUES ";



    // Arrays with JSON fields for every file
    public static String[]  productsJsonFields = {"id", "name"};
    public static String[] salesJsonFields = {"sale_id", "seller_id", "product_id", "quantity", "date"};
    public static String[] salesmenJsonFields = {"id", "last_name", "first_name"};
    public static String[] stockJsonFields = {"seller_id", "product_id", "price", "quantity"};

}
