package DatabaseOperations;

/**The class used to store some constants in the one place*/
public class ConstantsContainer {

    // Path to JSON with products
    public static String productsFilePath = "input_data/goods.json";

    // Path to JSON with sales
    public static String salesFilePath = "input_data/sales.json";

    // Path to JSON with salesmen
    public static String salesmenFilePath = "input_data/salesmen.json";

    // Path to json with Stock
    public static String stockFilePath = "input_data/stock.json";

    // Path to SQLite database file
    public static String databaseFilePath = "jdbc:sqlite:database/database.db";

    // The table generated by SQLite which we can't delete or modify, but it's seen in the table list
    public static String tableToIgnore = "sqlite_sequence";

    // The flag for the logger mode on/of
    public static boolean PROCESSING_LOGGER = true;



    // Starts of SQL Queries for the data insertion
    public static String productsInsertionInit = "INSERT INTO Products(ProductID, ProductName) VALUES ";
    public static String salesInsertInit = "INSERT INTO Sales(SaleID, SellerID, ProductID, QuantitySold, SaleDate) VALUES ";
    public static String salesmenInsertInit = "INSERT INTO Sellers(SellerID, FirstName, LastName) VALUES ";
    public static String stockInsertInit = "INSERT INTO Stock(SellerID, ProductID, Price, Quantity) VALUES ";



    // Arrays with JSON fields for every file
    public static String[]  productsJsonFields = {"id", "name"};
    public static String[] salesJsonFields = {"sale_id", "seller_id", "product_id", "quantity", "date"};
    public static String[] salesmenJsonFields = {"id", "last_name", "first_name"};
    public static String[] stockJsonFields = {"seller_id", "product_id", "price", "quantity"};


    // Output Values
    public static String oMostProductsHolder = "output/task1/most_products_owner(t1_v0).json";
    public static String oLeastPrice = "output/task1/least_price(t1_v1).json";
    public static String oGeneralStock = "output/task1/general_stock(t1_v2).json";
    public static String oGeneralSold = "output/task1/general_sold(t1_v3).json";
    public static String oTopFiveSellers = "output/task1/top_five_sellers(t1_v4).json";
    public static String oMostPopularGoods = "output/task1/most_popular_goods(t1_v5).json";

    public static String oSellsDistribution = "output/task2/sells_distribution(t2_v0).json";
    public static String oFiveBestDates = "output/task2/five_best_dates(t2_v1).json";
    public static String oAvgSells = "output/task2/avg_sells(t2_v2).json";


}
